kind = "web"
previewPath = "/"
title = "INFINITYPHONE ESTOQUE"
version = "1.0.0"
id = "artifacts/infinityphone"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 23771

[services.development]
run = "pnpm --filter @workspace/infinityphone run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/infinityphone", "run", "build" ]
publicDir = "artifacts/infinityphone/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "23771"
BASE_PATH = "/"
